baseurl = "https://piotrkowalczuk.github.io/"
title = "Piotr Kowalczuk Blog"
description = ""
theme = "ghostwriter"
languageCode = "pl"
copyright = "Piotr Kowalczuk"
googleAnalytics = "UA-50599199-4"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true

disqusShortname = "piotrkowalczuk"

[Author]
    name = "Piotr Kowalczuk"
    profile = "https://piotrkowalczuk.github.io"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Clear is better than clever"
    description = "Golang Development"
    github = "https://github.com/piotrkowalczuk"
    linkedin = "https://linkedin.com/in/piotr-kowalczuk-8a870480/"
    stackoverflow = "https://stackoverflow.com/users/1315205/piotr-kowalczuk"
    opengraph = true
    shareTwitter = true
    shareLinkedIn = true

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1